### ISSUE TITLE
Loading problem Waterfall (BungeeCord)

### ISSUE THREAD

**Issue by Patatone** [MinecraftMarket/MinecraftMarket-Plugin#29]
`[06:53:05] [main/INFO]: Using mbed TLS based native cipher.
[06:53:05] [main/INFO]: Using zlib based native compressor.
[06:53:05] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178
[06:53:05] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[06:53:05] [main/INFO]: Epoll is working, utilising it!
[06:53:05] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[06:53:05] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[06:53:05] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[06:53:05] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[06:53:05] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[06:53:05] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[06:53:05] [main/INFO]: Attempting to update plugin from null to ModuleVersion(build=178, git=dd9c358)
[06:53:05] [main/INFO]: Attempting to Jenkins download module cmd_alert v178
[06:53:06] [main/INFO]: Download complete
[06:53:06] [main/INFO]: Attempting to update plugin from null to ModuleVersion(build=178, git=dd9c358)
[06:53:06] [main/INFO]: Attempting to Jenkins download module cmd_find v178
[06:53:06] [main/INFO]: Download complete
[06:53:06] [main/INFO]: Attempting to update plugin from null to ModuleVersion(build=178, git=dd9c358)
[06:53:06] [main/INFO]: Attempting to Jenkins download module cmd_list v178
[06:53:06] [main/INFO]: Download complete
[06:53:06] [main/INFO]: Attempting to update plugin from null to ModuleVersion(build=178, git=dd9c358)
[06:53:06] [main/INFO]: Attempting to Jenkins download module cmd_send v178
[06:53:06] [main/INFO]: Download complete
[06:53:06] [main/INFO]: Attempting to update plugin from null to ModuleVersion(build=178, git=dd9c358)
[06:53:06] [main/INFO]: Attempting to Jenkins download module cmd_server v178
[06:53:06] [main/INFO]: Download complete
[06:53:06] [main/INFO]: Attempting to update plugin from null to ModuleVersion(build=178, git=dd9c358)
[06:53:06] [main/INFO]: Attempting to Jenkins download module reconnect_yaml v178
[06:53:06] [main/INFO]: Download complete
[06:53:06] [main/WARN]: Could not load plugin from file plugins/MinecraftMarket-3.6.7.jar
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=author for JavaBean=PluginDescription(name=MinecraftMarket, main=com.minecraftmarket.minecraftmarket.bungee.MCMarket, version=3.6.7, author=null, depends=[], softDepends=[], file=null, description=null)
 in 'reader', line 1, column 1:
    name: MinecraftMarket
    ^
No suitable constructor with 2 arguments found for class java.lang.String
 in 'reader', line 4, column 9:
    author: [Tck13, R4G3_BABY]
            ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:383) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:270) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
Caused by: org.yaml.snakeyaml.error.YAMLException: No suitable constructor with 2 arguments found for class java.lang.String
	at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:584) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:247) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	... 12 more`

**Comment by Tck13** [comment]
Dear Patatone,

There will come a fix on SpigotMC in the next coming 48 hours, but I have here that version already for you: https://www.dropbox.com/s/4jkxded8a8v7wxx/MinecraftMarket-3.6.8.jar?dl=0

Sorry for the trouble!

Kind regards,
Tycho
MinecraftMarket

**Comment by Patatone** [comment]
Did you forget to upload it on Spigot?

**Comment by Tck13** [comment]
Dear @Patatone,

I can't upload it self to the SpigotMC page and who needs to do that is very busy, so yes it's not done yet but not forgotten.

Kind regards,
Tycho
MinecraftMarket
