### ISSUE TITLE
Shutdown error

### ISSUE THREAD

**Issue by LogGits** [MinecraftMarket/MinecraftMarket-Plugin#32]
```
WARN 18/06/2018 00:17:49
00:17:49[MinecraftMarket] Plugin MinecraftMarket v3.6.7 generated an exception while executing task 1858930
Console 18/06/2018 00:17:49
00:17:49org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:478) ~[patched_1.12.2.jar:git-Paper-1445]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:146) ~[patched_1.12.2.jar:git-Paper-1445]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:129) ~[patched_1.12.2.jar:git-Paper-1445]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:112) ~[patched_1.12.2.jar:git-Paper-1445]
at com.minecraftmarket.minecraftmarket.bukkit.tasks.SignsTask.lambda$updateSigns$4(SignsTask.java:136) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1445]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1445]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1445]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Tck13** [comment]
Dear @LogGits,

Reloading is not supported. Doing so may cause bugs and memory leaks. It is recommended to restart instead of using /reload. 

Kind regards,
Tycho
MinecraftMarket

**Comment by LogGits** [comment]
It wasn't a report, it was a restart.

**Comment by Tck13** [comment]
Dear @LogGits,

Okay - onDisable anyway, as told you before I should prevent this from happening in a next release.

Kind regards,
Tycho
MinecraftMarket
